### ISSUE TITLE
Newly installed Morphic won't run if installed over previous version

### ISSUE THREAD

**Issue by nachochris** [oregondesignservices/MorphicLiteSolutions#4]
Have Windows 10 with MorphicLite running. Click on install.  Install script will ask you if you want stop running Morphic. Click Yes.   Installation proceeds.  Newly installed exe will not run.

**Comment by nachochris** [comment]
the work-round was to delete old Morphic exe and then install

**Comment by owenpshaw** [comment]
Opened in wrong project.  See issue in MorphicLiteClientWindows
